name: Upload package to pypi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: publish

    steps:
    - uses: actions/checkout@v3
    - name: Build and Publish to pypi
      uses: JRubics/poetry-publish@v1.17
      with:
        python_version: "3.11"
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: ${{ vars.PYPI_REPOSITORY }}
